spring:
  application:
    name: authorization_server

  threads:
    virtual:
      enabled: true

  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9000

server:
  port: 9000